config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :videos
  resources :reviews
  resources :products
  resources :news_articles
  resources :users do
    member do
      post 'add_to_cart'
    end
  end

  get '/features', to: 'videos#features'
  get '/log_in', to: 'pages#log_in'
  get '/view_cart', to: 'carts#view_cart'

  post 'sessions', to: 'sessions#create'

  delete '/sign_out', to: 'sessions#destroy'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :items
  has_many :products, through: :items
  belongs_to :user
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  delegate :name, :desc, :price, :filepicker_url, to: :product

  def quantity
    super || 0
  end

end

app/models/news_article.rb
class NewsArticle < ActiveRecord::Base
end

app/models/news_articles.rb
class NewsArticle
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  validates_presence_of :name, :desc, :price, :category
  Categories = ['Shirts', 'Shoes', 'Shorts', 'Pants', 'Hat', 'Socks', 'Beanies']

  def exerpt
    return desc if desc.length < 35
    desc[0..35] + '...'
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  include Authem::User
  has_one :cart
  has_many :reviews
  validates_presence_of :email, :password_digest

  def cart
    super || create_cart
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  Categories = ['Full Part', 'Game Of Skate', 'Bangin']
  validates_presence_of :name, :desc, :filepicker_url

  def exerpt
    return desc if desc.length < 35
    desc[0..60] + '...'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  authem_for :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def view_cart
    if current_user.present?
      @cart = current_user.cart
    end
  end
end

app/controllers/news_articles_controller.rb
class NewsArticlesController < ApplicationController
  def index
  end

  def new
    @news_article = NewsArticle.new
  end

  def create
    @news_article = NewsArticle.new(news_article_params)
    if @news_article.save
      redirect_to news_articles_path
    else
      render new_news_article_path
    end
  end

  def show
  end

  def news_article_params
    params.require(:news_article).permit(
      :title,
      :content,
      :filepicker_url
    )
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @video = Video.last
  end

  def features
  end

  def log_in
    @user = User.new
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params[:category].present?
      @products = Product.where(category: params[:category])
    else
      @products = Product.all
    end
    @categories = Product.pluck(:category).uniq
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render new_product_path
    end
  end

  def product_params
    params.require(:product).permit(
      :name,
      :desc,
      :price,
      :category,
      :filepicker_url
    )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to products_path
    else
      render product_path(@product)
    end
  end

  def review_params
    params.require(:review).permit(
      :text,
      :rating,
      :product_id,
      :user_id
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      sign_in(user)
      redirect_to videos_path
    else
      redirect_to log_in_path
    end
  end

  def destroy
    sign_out_user
    redirect_to videos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def add_to_cart
    item.quantity = item.quantity + added_quantity
    item.save
    redirect_to product_path(item.product)
  end

  def create
    @user = User.new(user_params)
    sign_in(@user)
    if @user.save
      redirect_to videos_path
    else
      redirect_to sign_in_path
    end
  end

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation
    )
  end

  private

  def added_quantity
    params.fetch(:quantity, 1).to_i
  end

  def item
    @item ||= current_user.cart.items.find_or_initialize_by(product_id: params[:product_id])
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    if params[:search].present?
      @videos = Video.fuzzy_search(params[:search]).order('created_at DESC')
    else
      @videos = Video.order('created_at DESC')
    end
    @recent_video = Video.order('created_at DESC').limit(5)
  end

  def show
    @video = Video.find(params[:id])
    @recent_video = Video.order('created_at DESC').limit(5)
  end

  def new
    @video = Video.new
  end

  def features
    if params[:category].present?
      @videos = Video.where(category: params[:category])
    else
      @videos = Video.all
    end
    @categories = Video.pluck(:category).uniq
  end

  def create
   @video = Video.new(video_params)
   if @video.save
     redirect_to videos_path
   else
     render new_video_path
   end
  end

  def video_params
    params.require(:video).permit(
      :name,
      :desc,
      :filepicker_url,
      :category
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/view_cart.html.haml
%div
  -if current_user.present?
    %p#your_cart
    Cart:
    = current_user.cart.items.count
    - current_user.cart.items.each do |item|
      %ul.cart
        %li= item.name
        %li.desc= item.desc
        %p.desc
          price:
          = item.price
        %p.quantity
          quantity:
          = item.quantity
        %div= filepicker_image_tag item.filepicker_url
    %p#price
      Total Price:
  -else
    %p Must be signed in to view cart

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BerricsFake</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
%head
  %title BerricsFake
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  = filepicker_js_include_tag
  = csrf_meta_tags
%body
  %h1 Berrics
  %div.user_links
    -if current_user.present?
      %span= link_to 'Sign Out', sign_out_path, method: :delete
      %span= link_to 'Create Video', new_video_path
    -else
      %span= link_to 'Log In', log_in_path
      = link_to 'Cart', view_cart_path
  %div
    = link_to 'Videos', videos_path, class: 'header'
    = link_to 'Feature', features_path, class: 'header'
    = link_to 'News', news_articles_path, class: 'header'
    = link_to 'Store', products_path, class: 'header'
  = yield

app/views/news/index.html.haml
%h1 News

app/views/news_articles/index.html.haml
%div= link_to 'Create News', new_news_article_path

app/views/news_articles/new.html.haml
%div.create_news
  %ul
    = form_for(@news_article) do |f|
      %li= f.label :title
      %li= f.text_field :title

      %li= f.label :content
      %li= f.text_area :content

      %li= f.label :Image
      %li= f.filepicker_field :filepicker_url

      %li= f.submit

app/views/pages/features.html.haml
%h1 Features

%div

app/views/pages/home.html.haml
%ul
  - if @video.present?
    %li.home_video= filepicker_image_tag @video.filepicker_url
  %li.enter= link_to 'Enter The Berrics', videos_path

app/views/pages/log_in.html.haml
%div.sign_up
  %div.left
    %h1 Sign Up

    = form_for(@user) do |f|
      %ul.sign_up_li
        %li= f.label :email
        %li= f.text_field :email

        %li= f.label :password
        %li= f.password_field :password

        %li= f.label :password_confirmation
        %li= f.password_field :password_confirmation

        %li= f.submit 'Sign Up'

  %div.right
    %h1 Sign In

    = form_tag(sessions_path) do
      %ul.sign_up_li
        %li= label_tag :email
        %li= text_field_tag :email

        %li= label_tag :password
        %li= password_field_tag :password

        %li= submit_tag 'Sign Up'

app/views/products/index.html.haml
= link_to 'Create Product', new_product_path
%div.products
  %div.categories
    %p#category_name Clothing
    - @categories.each do |category|
      %li= link_to category, products_path(category: category), class: 'category_links'

  %table.product_list
    - @products.each do |product|
      %td
        %li= link_to(filepicker_image_tag(product.filepicker_url), product_path(product.id))
        %li= product.name
        %li= product.exerpt
        %p= link_to product.category
        %p
          $
          = product.price

app/views/products/new.html.haml
%ul
  = form_for(@product) do |f|
    %li= f.label :name
    %li= f.text_field :name

    %li= f.label :desc
    %li= f.text_area :desc

    %li= f.select :category,  Product::Categories, prompt: 'Select Category'

    %li= f.label :price
    %li= f.number_field :price, value: 1 , min: 1

    %li= f.label :Image
    %li= f.filepicker_field :filepicker_url

    %li= f.submit

app/views/products/show.html.haml
%h1 yo

%div.full_size
  %li= @product.name
  %li= filepicker_image_tag @product.filepicker_url
  %li= @product.desc
  %li
    $
    = @product.price
  %li= @product.category
  - if current_user.present?
    %li
      = form_tag add_to_cart_user_path(current_user) do
        = hidden_field_tag :product_id, @product.id
        = number_field_tag :quantity, 1,  min: 1, max: 10
        = submit_tag 'Add To Cart'
  - if current_user.present?
    %div
      %p Leave a Review
      = form_for(@review) do |f|
        = hidden_field :product_id, @product.id
        = hidden_field :user_id, current_user.id
        %li= f.label :text
        %li= f.text_area :text

        %li= f.label :rating
        %li= f.number_field :rating, min: 1, max: 10
        %li= f.submit 'Leave Review'

%div.review_list
  Reviews
  - @product.reviews.each do |review|
    = review.text
    = review.rating

app/views/videos/features.html.haml
%ul.features
  %p#features FEATURES
  - @categories.each do |category|
    %td= link_to category, videos_path(category: category), class: 'features_links'

app/views/videos/index.html.haml
%div
  %div.search
    = form_tag(videos_path, method: :get) do
      = text_field_tag :search, nil, placeholder: 'Search Videos', class: 'seach_bar'
      = submit_tag 'Search', class: 'search_button'
  %ul.videos
    - @videos.each do |video|
      %li.name= video.name
      %li= filepicker_image_tag video.filepicker_url
      %li.desc
        = video.desc
        = link_to video.category

  %div.right_side_info
    %ul.right_ul
      %div.recent_div
        %p#recent_p Recent Videos
      - @recent_video.each do |recent|
        %span.recent_image= link_to(filepicker_image_tag(recent.filepicker_url), video_path(recent.id))
        %p.recent_info
          %span#recent_name= recent.name
          = recent.exerpt

    %ul.right_ul
      %div.recent_div
        %p#recent_p Recent News

app/views/videos/new.html.haml
%h1 Create that Bit

%ul.left
  = form_for(@video) do |f|
    %li= f.label :name
    %li= f.text_field :name, placeholder: 'Video Name'

    %li= f.label :description
    %li= f.text_area :desc, placeholder: 'Description'

    %li= f.label :category
    %li= f.select :category, Video::Categories, prompt: 'Select Category'

    %li= f.label :filepicker_url
    %li= f.filepicker_field :filepicker_url

    %li= f.submit 'Create Video'

app/views/videos/show.html.haml
%ul.videos
  %li= @video.name
  %li= filepicker_image_tag @video.filepicker_url
  %li= @video.desc

%div.right_side_info
  %ul.right_ul
    %div.recent_div
      %p#recent_p Recent Videos
    - @recent_video.each do |recent|
      %span.recent_image= link_to(filepicker_image_tag(recent.filepicker_url), video_path(recent.id))
      %li.recent_name= recent.name
      %li.recent_desc= recent.desc

  %ul.right_ul
    %div.recent_div
      %p#recent_p Recent News